sort: sort.cpp utill.cpp
			g++ -g sort.cpp utill.cpp -o ../bin/sort.exe
make_bat: make_bat.c utill.c
			g++ -g make_bat.cpp utill.c -o ../bin/make_bat.exe
csv_to_data: csv_to_data.c utill.c
			g++ -g csv_to_data.c utill.c config/csv.c -o ../bin/csv_to_data.exe