sort: sort.c utill.c
			g++ -O3 -mtune=native -march=native -mfpmath=both main.cpp
			g++ sort.c utill.c -o ../../bin/sort.exe -O3 -mtune=native -march=native -mfpmath=both
make_bat: make_bat.c utill.c
			g++ -g make_bat.c utill.c -o ../../bin/make_bat.exe
csv_to_data: csv_to_data.c utill.c
			g++ -g csv_to_data.c utill.c config/csv.c -o ../../bin/csv_to_data.exe