sort: sort/sort.c config/data_logger.c utill.c
			gcc -g sort/sort.c config/data_logger.c utill.c -o ../bin/sort
make_bat: make_bat/make_bat.c utill.c
			gcc -g make_bat/make_bat.c utill.c -o ../bin/make_bat