#!/bin/bash
echo -e "sort all data"
echo -e "input total number:"
read NUM
echo -e "total num is ${NUM}"
echo -e "input initial data number(separated space):"
declare -a INIT_NUM
read -a INIT_NUM
echo -e "initial data are ${INIT_NUM[*]}"
echo -e "input input directory path:"
read IN_PATH
echo -e "input output directory path:"
read OUT_PATH
echo -e "total number: ${NUM}"
echo -e "initial     : ${INIT_NUM[*]}"
echo -e "input path  : ${IN_PATH}"
echo -e "output path : ${OUT_PATH}"
echo "Continue? [y/N] > "
read answer
if [ "${answer}" != "y" ]; then
  echo "Aborted."
  exit 1
fi
for i in $(seq 1 $NUM)
do
    init_flg=0
    for j in "${INIT_NUM[@]}"
    do
        if [ $i = $j ]; then
            init_flg=1
            break
        fi
    done
    ./sort $i $init_flg $IN_PATH $OUT_PATH
done