#!/bin/bash
echo -e "input total number:"
read NUM
echo -e "input initial data number(separated space):"
declare -a INIT_NUM
read -a INIT_NUM
echo -e "initial data are ${INIT_NUM[*]}"
for i in $(seq 1 $NUM)
do
    echo -e "i : ${i}"
    for j in "${INIT_NUM[@]}"
    do
        echo -e "j : ${j}"
    done
done